# creation rules are evaluated sequentially, the first match wins
creation_rules:
        - path_regex: environments/health-dev\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:218381940040:key/d83c3ae8-20df-418b-b8bb-5bdbe09e0f2c'