# Common Labels
labels:
  app: "egov-rn-service"
  group: "core"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "egov-rn-service"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "egov_rn_schema"
    image:
      repository: "egov-rn-service-db"

# Container Configs
image:
  repository: "egov-rn-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/egov-rn-service/health"
  readinessProbePath: "/egov-rn-service/health"
appType: "java-spring"
tracing-enabled: true
persist-yml-path: "file:///work-dir/health-configs/egov-persister/apportion-persister.yml,file:///work-dir/health-configs/egov-persister/property-services-registry.yml,file:///work-dir/health-configs/egov-persister/billing-services-persist.yml,file:///work-dir/health-configs/egov-persister/egf-bill.yaml,file:///work-dir/health-configs/egov-persister/egov-user-event-persister.yml,file:///work-dir/health-configs/egov-persister/egov-workflow-v2-persister.yml,file:///work-dir/health-configs/egov-persister/firenoc_persiter.yaml,file:///work-dir/health-configs/egov-persister/hrms-employee-persister.yml,file:///work-dir/health-configs/egov-persister/pdf-generator.yml,file:///work-dir/health-configs/egov-persister/pg-service-persister.yml,file:///work-dir/health-configs/egov-persister/pgr.v3.yml,file:///work-dir/health-configs/egov-persister/property-services.yml,file:///work-dir/health-configs/egov-persister/pt-calculator-v2-persister.yml,file:///work-dir/health-configs/egov-persister/pt-drafts.yml,file:///work-dir/health-configs/egov-persister/pt-persist.yml,file:///work-dir/health-configs/egov-persister/tl-billing-slab-persister.yml,file:///work-dir/health-configs/egov-persister/tl-calculation-persister.yml,file:///work-dir/health-configs/egov-persister/tradelicense-persister-bpachanges.yml,file:///work-dir/health-configs/egov-persister/uploader-persister.yml,file:///work-dir/health-configs/egov-persister/collection-migration-persister.yml,file:///work-dir/health-configs/egov-persister/water-persist.yml,file:///work-dir/health-configs/egov-persister/water-meter.yml,file:///work-dir/health-configs/egov-persister/assessment-persister.yml,file:///work-dir/health-configs/egov-persister/sewerage-persist.yml,file:///work-dir/health-configs/egov-persister/bpa-persister.yml,file:///work-dir/health-configs/egov-persister/egov-rn-service-persister.yml"
heap: "-Xmx192m -Xms192m"
java-args: ""

# Additional Container Envs
env: |
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: egov-rn-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  {{- if index .Values "global" "tracer-errors-provideexceptionindetails" }}
  - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: tracer-errors-provideexceptionindetails
  {{- end }}
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: JAVA_ENABLE_DEBUG
    value: {{ index .Values "java-enable-debug" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false" 
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
